#!/usr/bin/env bash

userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$XDG_CONFIG_HOME/X11/xmodmap"
xresourcesd="$XDG_CONFIG_HOME/X11/xresources.d"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge -I"$xresourcesd" "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Extra configurations
# This should merge in configurations for things such as nord and urxvt
# if [ -d "$xresourcesd" ]; then
#     for f in "${xresourcesd}"/*; do
#         xrdb -merge "$f"
#     done
#     unset f
# fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3 --shmlog-size=26214400
#exec i3
