export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

export DOTFILES="$HOME/.dotfiles"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$XDG_CONFIG_HOME/local/share"
export XDG_CACHE_HOME="$XDG_CONFIG_HOME/cache"

# X11
export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

# other
export I3_CONFIG="$XDG_CONFIG_HOME/i3"
export VIMCONFIG="$XDG_CONFIG_HOME/vim"

# Zsh Environment variables
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/.zhistory"
export HISTSIZE=10000
export SAVEHIST=10000
#export TERM=terminator

# Rust Up
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# Docker
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"

# Javascript, Node, NPM
export NVM_DIR="$XDG_DATA_HOME/nvm"

# VIM / NVIM
export VIMCONFIG=~/.config/nvim
export VIMDATA=~/.local/share/nvim

# editor
export EDITOR="vim"
export VISUAL="vim"

